# hosts/nixos-gnome/configuration.nix
#
# Minimal NixOS system configuration — GNOME sub-task.
#
# WHAT THIS FILE IS:
#   The system-level declaration for a minimal NixOS install running GNOME.
#   It owns everything below the user-environment line:
#     - Boot loader
#     - Kernel
#     - Hardware
#     - Display manager (GDM)
#     - Desktop environment (GNOME Shell)
#     - System-level services (NetworkManager, PipeWire, printing)
#     - User account declaration (UID 1000)
#     - Exclusion of GNOME bloatware
#
# WHAT THIS FILE IS NOT:
#   It does not manage extensions, dconf settings, user apps, or dotfiles.
#   All of that lives in modules/de/gnome.nix, applied via Home Manager.
#
# HOW IT FITS INTO CYPHER-SYSTEM:
#   This is the nixos-gnome host — the proof-of-concept NixOS install for the
#   GNOME sub-task. Eventually it merges into hosts/nixos/configuration.nix
#   when the main CypherOS sequence reaches Phase 9.
#
# TO APPLY:
#   sudo nixos-rebuild switch --flake .#nixos-gnome
#   home-manager switch --flake .#cypher-whisperer@nixos-gnome

{ config, pkgs, lib, ... }:

{
  imports = [
    # hardware-configuration.nix is auto-generated by nixos-generate-config
    # during install. It declares your specific disk UUIDs, CPU, and detected
    # hardware. Keep it alongside this file and import it here.
    ./hardware-configuration.nix
  ];


  # ─────────────────────────────────────────────────────────────────────────────
  # BOOT LOADER
  # ─────────────────────────────────────────────────────────────────────────────
  # systemd-boot is the leading candidate for CypherOS (see OQ6 in architecture).
  # It handles a shared ESP cleanly — each OS gets its own loader entry in
  # /boot/EFI/<os-name>/ and systemd-boot presents them all at startup.
  #
  # efi.canTouchEfiVariables = true: lets NixOS write its boot entry to NVRAM.
  # Required for systemd-boot to work on most UEFI firmware.
  boot.loader = {
    systemd-boot.enable      = false;
    grub.enable = true;
    grub.efiSupport = true;
    grub.device = "nodev";
    efi.canTouchEfiVariables = true;
    efi.efiSysMountPoint = "/boot";
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # KERNEL EXTRA MODULES
  # ─────────────────────────────────────────────────────────────────────────────
  # btrfs is built into the mainline kernel — no extra module needed.
  # Add any hardware-specific modules here if required.
  # boot.kernelModules = [ ];


  # ─────────────────────────────────────────────────────────────────────────────
  # NETWORKING
  # ─────────────────────────────────────────────────────────────────────────────
  # NetworkManager handles WiFi and wired connections. The GNOME network
  # indicator and Settings panel talk to it via D-Bus.
  # hostName: set this to whatever you want this machine to identify as.
  networking = {
    hostName      = "cypher-nixos";
    networkmanager.enable = true;
  };


  # ─────────────────────────────────────────────────────────────────────────────
  # LOCALE & TIME
  # ─────────────────────────────────────────────────────────────────────────────
  time.timeZone = "Africa/Nairobi";

  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS        = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT    = "en_US.UTF-8";
    LC_MONETARY       = "en_US.UTF-8";
    LC_NAME           = "en_US.UTF-8";
    LC_NUMERIC        = "en_US.UTF-8";
    LC_PAPER          = "en_US.UTF-8";
    LC_TELEPHONE      = "en_US.UTF-8";
    LC_TIME           = "en_US.UTF-8";
  };


  # ─────────────────────────────────────────────────────────────────────────────
  # KEYBOARD (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # These settings apply at the virtual console (TTY) level and to the X/Wayland
  # session before GNOME's own input-sources settings take over.
  # The xkb-options here match your dconf input-sources settings exactly,
  # so the remapping is consistent from TTY login through to the desktop.
  services.xserver.xkb = {
    layout  = "us";
    options = "ctrl:swapcaps,menu:super,altwin:menu_win";
  };


  # ─────────────────────────────────────────────────────────────────────────────
  # DISPLAY SERVER + GNOME
  # ─────────────────────────────────────────────────────────────────────────────
  # xserver.enable = true is required even for Wayland sessions on NixOS —
  # it enables the X11 infrastructure that GDM and some Wayland compositors
  # still depend on (XWayland, xauth, etc.).
  #
  # GDM (GNOME Display Manager) is the login screen. It handles session
  # selection and hands off to either the GNOME Wayland or X11 session.
  #
  # desktopManager.gnome.enable pulls in gnome-shell, gnome-session,
  # gnome-control-center, nautilus, and the core GNOME session infrastructure.
  # It does NOT pull in every GNOME app — that's controlled separately below.
  services.xserver.enable = true;

  services.displayManager.gdm = {
    enable    = true;
    wayland   = true;   # prefer Wayland sessions; GDM falls back to X11 if needed
  };

  services.desktopManager.gnome.enable = true;


  # ─────────────────────────────────────────────────────────────────────────────
  # GNOME BLOATWARE EXCLUSION
  # ─────────────────────────────────────────────────────────────────────────────
  # services.desktopManager.gnome.enable pulls in a default set of GNOME apps.
  # environment.gnome.excludePackages lets you surgically remove the ones you
  # don't want. This gives you a minimal GNOME — only what you explicitly
  # install via Home Manager, plus the essential shell infrastructure.
  #
  # Everything listed here would otherwise be installed system-wide automatically.
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour          # the first-run tour wizard — not needed
    yelp                # GNOME help browser — documentation you'll never open
    totem               # GNOME Videos — you use vlc
    gnome-maps          # GNOME Maps
    gnome-weather        # GNOME Weather widget
    gnome-contacts       # GNOME Contacts
    gnome-music          # GNOME Music — you use spotify
    epiphany             # GNOME Web (the built-in browser) — you use brave/firefox
    geary                # GNOME Mail client — you use proton-mail
    gnome-calendar       # optional: keep if you use it, exclude if not
    simple-scan          # scanner app — keep if you have a scanner, exclude if not
    gnome-clocks         # keep or exclude based on preference
    gnome-characters     # character/emoji picker — borderline useful
  ];


  # ─────────────────────────────────────────────────────────────────────────────
  # SOUND
  # ─────────────────────────────────────────────────────────────────────────────
  # PipeWire is the modern audio/video server. It handles both audio (replacing
  # PulseAudio) and screen capture (replacing PulseAudio's monitor sources and
  # the older JACK ecosystem).
  #
  # sound.enable = false: disables the legacy ALSA-only sound config. Required
  # when using PipeWire — they conflict if both are active.
  #
  # wireplumber is the session manager that routes audio streams between apps
  # and hardware via PipeWire. Think of PipeWire as the router and WirePlumber
  # as the traffic controller.
  hardware.pulseaudio.enable = false;   # PipeWire replaces PulseAudio

  services.pipewire = {
    enable            = true;
    alsa.enable       = true;    # ALSA compatibility layer
    alsa.support32Bit = true;    # 32-bit ALSA support (needed for Steam/Wine)
    pulse.enable      = true;    # PulseAudio compatibility layer (most apps use this API)
    wireplumber.enable = true;
  };


  # ─────────────────────────────────────────────────────────────────────────────
  # PRINTING
  # ─────────────────────────────────────────────────────────────────────────────
  # CUPS handles printing. avahi enables mDNS printer discovery on the local
  # network (the "Add Printer" dialog in GNOME Settings finds network printers via this).
  services.printing.enable = true;
  services.avahi = {
    enable   = true;
    nssmdns4 = true;
    openFirewall = true;
  };


  # ─────────────────────────────────────────────────────────────────────────────
  # BLUETOOTH
  # ─────────────────────────────────────────────────────────────────────────────
  hardware.bluetooth = {
    enable      = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;


  # ─────────────────────────────────────────────────────────────────────────────
  # DOCKER
  # ─────────────────────────────────────────────────────────────────────────────
  # Docker daemon runs at the system level. The docker-client CLI is installed
  # by Home Manager. The daemon must be here.
  # extraGroups below adds cypher-whisperer to the docker group so you can run
  # docker commands without sudo.
  virtualisation.docker.enable = true;


  # ─────────────────────────────────────────────────────────────────────────────
  # UNFREE PACKAGES (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # This allows unfree packages at the system configuration level.
  # Home Manager's gnome.nix has its own allowUnfree for user-level packages.
  # Both are needed — they operate in different package scopes.
  nixpkgs.config.allowUnfree = true;


  # ─────────────────────────────────────────────────────────────────────────────
  # NIX SETTINGS
  # ─────────────────────────────────────────────────────────────────────────────
  # experimental-features: flakes and nix-command are not yet stable API in Nix,
  # so they're gated behind this flag. You need both enabled to use flakes.
  # nix-command is the unified `nix` CLI (nix build, nix run, nix shell, etc.).
  nix.settings = {
    experimental-features = [ "nix-command" "flakes" ];
    # trusted-users allows cypher-whisperer to run nix as a trusted user —
    # necessary for `home-manager switch` to work with the multi-user daemon.
    trusted-users = [ "root" "cypher-whisperer" ];
  };


  # ─────────────────────────────────────────────────────────────────────────────
  # USER ACCOUNT
  # ─────────────────────────────────────────────────────────────────────────────
  # This is the canonical user declaration for cypher-whisperer on NixOS.
  # The uid = 1000 is the universal truth across the CypherOS fleet — every OS
  # recognises this user by UID number, not by username string. File ownership
  # on shared BTRFS subvolumes resolves correctly because UID 1000 is consistent.
  #
  # isNormalUser = true: creates a home directory, adds the user to the
  # 'users' group, and enables login. (As opposed to a system user.)
  #
  # extraGroups: the groups that give this user elevated access to hardware
  # and services. Each group is explained inline.
  users.users.cypher-whisperer = {
    isNormalUser = true;
    uid          = 1000;
    description  = "Cypher Whisperer";
    home         = "/home/cypher-whisperer";
    shell        = pkgs.zsh;
    extraGroups  = [
      "wheel"         # sudo access
      "networkmanager" # manage network connections without sudo
      "docker"        # run docker without sudo
      "audio"         # direct audio device access (belt-and-suspenders with PipeWire)
      "video"         # GPU/video device access
      "input"         # input device access (needed for some Wayland compositors)
    ];
  };

  # mutableUsers = false would make NixOS the sole authority on users —
  # passwd and adduser commands would be ignored. Leaving it true (the default)
  # for now since you may want to change passwords interactively. Revisit in
  # the hardening phase.
  # users.mutableUsers = false;


  # ─────────────────────────────────────────────────────────────────────────────
  # ZSH (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # Setting the user shell to pkgs.zsh above requires zsh to be enabled at the
  # system level — NixOS won't add it to /etc/shells otherwise, which breaks login.
  programs.zsh.enable = true;


  # ─────────────────────────────────────────────────────────────────────────────
  # SYSTEM PACKAGES
  # ─────────────────────────────────────────────────────────────────────────────
  # Packages listed here are installed system-wide (available to all users,
  # in the system PATH). Keep this minimal — user-space apps belong in
  # Home Manager (gnome.nix), not here.
  #
  # What belongs here: tools needed before Home Manager runs, or tools that
  # genuinely require system-level installation.
  environment.systemPackages = with pkgs; [
    git          # needed to clone the cypher-system flake repo itself
    curl         # needed for initial Nix/HM bootstrap commands
    vim          # emergency editor before HM applies neovim
    home-manager # the home-manager CLI must be on the system PATH
  ];


  # ─────────────────────────────────────────────────────────────────────────────
  # FONTS (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # Fonts declared here are available system-wide (GDM login screen, all users).
  # User fonts (in Home Manager) are in addition to these.
  fonts.packages = with pkgs; [
    cantarell-fonts
    noto-fonts
    noto-fonts-emoji
    fira-code
  ];


  # ─────────────────────────────────────────────────────────────────────────────
  # SYSTEM STATE VERSION
  # ─────────────────────────────────────────────────────────────────────────────
  # Like home.stateVersion in gnome.nix, this is set once at install time and
  # never changed. It tells NixOS which release the system config was written
  # against. It does NOT control which package versions you get — that's
  # determined by your flake inputs (the nixpkgs pin in flake.lock).
  system.stateVersion = "24.11";
}
