# hosts/nixos-gnome/configuration.nix
#
# Minimal NixOS system configuration — GNOME sub-task.
#
# WHAT THIS FILE IS:
#   The system-level declaration for a minimal NixOS install running GNOME.
#   It owns everything below the user-environment line:
#     - Boot loader
#     - Kernel
#     - Hardware
#     - Display manager (GDM)
#     - Desktop environment (GNOME Shell)
#     - System-level services (NetworkManager, PipeWire, printing)
#     - User account declaration (UID 1000)
#     - Exclusion of GNOME bloatware
#
# WHAT THIS FILE IS NOT:
#   It does not manage extensions, dconf settings, user apps, or dotfiles.
#   All of that lives in modules/de/gnome.nix, applied via Home Manager.
#
# HOW IT FITS INTO CYPHER-SYSTEM:
#   This is the nixos-gnome host — the proof-of-concept NixOS install for the
#   GNOME sub-task. Eventually it merges into hosts/nixos/configuration.nix
#   when the main CypherOS sequence reaches Phase 9.
#
# TO APPLY:
#   sudo nixos-rebuild switch --flake .#nixos-gnome
#   home-manager switch --flake .#cypher-whisperer@nixos-gnome

{
  config,
  pkgs,
  lib,
  inputs,
  ...
}:

{
  imports = [
    # hardware-configuration.nix is auto-generated by nixos-generate-config
    # during install. It declares a machine's specific disk UUIDs, CPU, and detected
    # hardware. You can chose to keep it alongside this file and import it here.
    # OR a cleaner alternative to prevent nixOS errros:
    #
    #/etc/nixos/hardware-configuration.nix
    #
    # hardware-configuration.nix is machine-specific generated output, but Nix
    # flakes require everything they reference to be tracked by git
    # (or at least present in the git tree — it doesn't have to be committed).

    # NixOS generates hardware-configuration.nix into /etc/nixos/ by default
    # during install. Referencing it by absolute path means it never needs to be
    # in your repo at all. The trade-off is your flake is no longer fully
    # self-contained — you need that file present on the machine.

    # However,since it contains nothing sensitive — just filesystem UUIDs,
    # kernel modules, and hardware quirks. It can belong in the repo alongside
    # the config that depends on it. Keeping everything self contained.
    ./hardware-configuration.nix
  
    # ── Feature Modules ──────────────────────────────────────────────────────  
    ../../modules/gaming/steam.nix
    # DevOps module subtree: containers, kubernetes, databases, iac, secrets.
    # Each subsystem is toggled individually below via devops.<n>.enable.
    ../../modules/devops

    # Virtualisation helpers: distrobox, winboat, vagrant, virt-viewer.
    ../../modules/virtualisation  
    ../../modules/virtualisation/kvm.nix
  ];

  # ─────────────────────────────────────────────────────────────────────────────
  # DEVOPS MODULE TOGGLES
  # ─────────────────────────────────────────────────────────────────────────────
  # Each line here activates an entire devops subsystem defined in modules/devops/.
  # Set to false (or remove the line) to exclude a subsystem from this host.
  # Useful when building a lighter config for a machine that doesn't need all tooling.
  devops.containers.enable  = true;  # Docker + Podman stacks, image tooling
  devops.kubernetes.enable  = false;  # k3s service, kubectl, Helm, k3d, kind
  devops.databases.enable   = true;  # PostgreSQL + Redis services, DB GUIs
  devops.iac.enable         = false;  # Terraform, OpenTofu, Ansible, Pulumi
  devops.secrets.enable     = false;  # sops, age, gnupg, vault

  # Virtualisation helpers toggle
  virtualisation.helpers.enable = false;  # distrobox, winboat, vagrant, virt-viewer

  # ─────────────────────────────────────────────────────────────────────────────
  # BOOT LOADER
  # ─────────────────────────────────────────────────────────────────────────────
  # systemd-boot is the leading candidate for CypherOS (see OQ6 in architecture).
  # It handles a shared ESP cleanly — each OS gets its own loader entry in
  # /boot/EFI/<os-name>/ and systemd-boot presents them all at startup.
  #
  # efi.canTouchEfiVariables = true: lets NixOS write its boot entry to NVRAM.
  # Required for systemd-boot to work on most UEFI firmware.
  boot.loader = {
    systemd-boot.enable = false;
    grub.enable = true;
    grub.efiSupport = true;
    grub.device = "nodev";
    grub.useOSProber = false; # enable on a multiboot machine
    efi.canTouchEfiVariables = true;
    efi.efiSysMountPoint = "/boot";
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # KERNEL EXTRA MODULES
  # ─────────────────────────────────────────────────────────────────────────────
  # btrfs is built into the mainline kernel — no extra module needed.
  # Add any hardware-specific modules here if required.
  # boot.kernelModules = [ ];

  # ─────────────────────────────────────────────────────────────────────────────
  # VENTOY AND OTHER FILESYSTEMS
  # ─────────────────────────────────────────────────────────────────────────────
  boot.supportedFilesystems = [
    "ntfs"
    "exfat"
    "vfat"
  ];
  #services.udev.packages = [ pkgs.usbutils];

  # ─────────────────────────────────────────────────────────────────────────────
  # NETWORKING
  # ─────────────────────────────────────────────────────────────────────────────
  # NetworkManager handles WiFi and wired connections. The GNOME network
  # indicator and Settings panel talk to it via D-Bus.
  # hostName: set this to whatever you want this machine to identify as.
  networking = {
    hostName = "cypher-nixos";
    networkmanager.enable = true;
    nameservers = [
      "1.1.1.1"
      "8.8.8.8"
    ];
  };
  # CONSIDER: handling DNS resolution, instead of the router (resolved approach)
  # services.resolved.enable = true;
  # services.resolved.fallbackDns = [ "1.1.1.1" "8.8.8.8" ];
  #
  # networking.networkmanager.enable = true;
  # networking.networkmanager.dns = "systemd-resolved";

  # ─────────────────────────────────────────────────────────────────────────────
  # LOCALE & TIME
  # ─────────────────────────────────────────────────────────────────────────────
  time.timeZone = "Africa/Nairobi";

  i18n.defaultLocale = "en_US.UTF-8";
  i18n.extraLocaleSettings = {
    LC_ADDRESS        = "en_US.UTF-8";
    LC_IDENTIFICATION = "en_US.UTF-8";
    LC_MEASUREMENT    = "en_US.UTF-8";
    LC_MONETARY       = "en_US.UTF-8";
    LC_NAME           = "en_US.UTF-8";
    LC_NUMERIC        = "en_US.UTF-8";
    LC_PAPER          = "en_US.UTF-8";
    LC_TELEPHONE      = "en_US.UTF-8";
    LC_TIME           = "en_US.UTF-8";
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # KEYBOARD (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # These settings apply at the virtual console (TTY) level and to the X/Wayland
  # session before GNOME's own input-sources settings take over.
  services.xserver.xkb = {
    layout = "us";
    options = "ctrl:swapcaps,menu:super,altwin:menu_win"; # REMOVED:
  };

  # The above approach worked for the Ctrl-Caps swap, but failed on Super-Menu
  # Let's attempt keyd approach.
  # The reason keyd wins here: XKB operates on a key symbol level and some Wayland
  # compositors (including GNOME's Mutter) selectively honour XKB options.
  # keyd operates on raw evdev events before any of that, so it's compositor-agnostic.
  # it intercepts at the input device level before the compositor sees the event, so it
  # works in both Wayland and X11, in TTYs, and everywhere.

  services.keyd = {
    enable = true;
    keyboards.default = {
      # Replace the specific keyboard ID below if necessary, or use "*"
      ids = [ "*" ];
      settings = {
        # ATTEMPT 1
        #      main = {
        #        # Caps Lock ↔ Ctrl (belt-and-suspenders with XKB swap)
        #        capslock = "leftcontrol";
        #        # Menu key → Super
        #        menu = "leftmeta";
        #      };
        # ATTEMPT 2
        main = {
          # Remap Menu key (KEY_CONTEXT_MENU) to Super (KEY_LEFTMETA)
          # Remap Super key (KEY_LEFTMETA) to Menu (KEY_CONTEXT_MENU)
          # Note: You may need to verify exact codes using "sudo keyd monitor"

          "KEY_CONTEXT_MENU" = "KEY_LEFTMETA";
          "KEY_LEFTMETA" = "KEY_CONTEXT_MENU";
        };
      };
    };
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # DISPLAY SERVER + GNOME
  # ─────────────────────────────────────────────────────────────────────────────
  # xserver.enable = true is required even for Wayland sessions on NixOS —
  # it enables the X11 infrastructure that GDM and some Wayland compositors
  # still depend on (XWayland, xauth, etc.).
  #
  # GDM (GNOME Display Manager) is the login screen. It handles session
  # selection and hands off to either the GNOME Wayland or X11 session.
  #
  # desktopManager.gnome.enable pulls in gnome-shell, gnome-session,
  # gnome-control-center, nautilus, and the core GNOME session infrastructure.
  # It does NOT pull in every GNOME app — that's controlled separately below.
  services.xserver.enable = true;

  services.displayManager.gdm = {
    enable = true;
    wayland = true; # prefer Wayland sessions; GDM falls back to X11 if needed
  };

  services.desktopManager.gnome.enable = true;

  # ─────────────────────────────────────────────────────────────────────────────
  # GNOME BLOATWARE EXCLUSION
  # ─────────────────────────────────────────────────────────────────────────────
  # services.desktopManager.gnome.enable pulls in a default set of GNOME apps.
  # environment.gnome.excludePackages lets you surgically remove the ones you
  # don't want. This gives you a minimal GNOME — only what you explicitly
  # install via Home Manager, plus the essential shell infrastructure.
  #
  # Everything listed here would otherwise be installed system-wide automatically.
  environment.gnome.excludePackages = with pkgs; [
    gnome-tour      # first-run tour wizard — not needed
    yelp            # GNOME help browser — documentation you'll never open
    totem           # GNOME Videos — you use vlc
    gnome-maps      # GNOME Maps
    gnome-weather   # GNOME Weather widget
    gnome-contacts  # GNOME Contacts
    gnome-music     # GNOME Music — you use spotify
    epiphany        # GNOME Web (built-in browser) — you use brave/firefox
    geary           # GNOME Mail client — you use proton-mail
    gnome-calendar
    simple-scan     # scanner app — keep if thou have a scanner, exclude if not
    gnome-clocks    # keep or exclude based on preference
    # gnome-characters   # character/emoji picker — borderline useful
  ];

  # ─────────────────────────────────────────────────────────────────────────────
  # SOUND
  # ─────────────────────────────────────────────────────────────────────────────
  # PipeWire is the modern audio/video server. It handles both audio (replacing
  # PulseAudio) and screen capture (replacing PulseAudio's monitor sources and
  # the older JACK ecosystem).
  #
  # sound.enable = false: disables the legacy ALSA-only sound config. Required
  # when using PipeWire — they conflict if both are active.
  #
  # wireplumber is the session manager that routes audio streams between apps
  # and hardware via PipeWire. Think of PipeWire as the router and WirePlumber
  # as the traffic controller.
  services.pulseaudio.enable = false; # PipeWire replaces PulseAudio

  services.pipewire = {
    enable              = true;
    alsa.enable         = true;         # ALSA compatibility layer
    alsa.support32Bit   = true;         # 32-bit ALSA support (needed for Steam/Wine)
    pulse.enable        = true;         # PulseAudio compatibility layer
    wireplumber.enable  = true;
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # PRINTING
  # ─────────────────────────────────────────────────────────────────────────────
  # CUPS handles printing. avahi enables mDNS printer discovery on the local
  # network (the "Add Printer" dialog in GNOME Settings finds network printers via this).
  services.printing.enable = true;
  services.avahi = {
    enable = true;
    nssmdns4 = true;
    openFirewall = true;
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # BLUETOOTH
  # ─────────────────────────────────────────────────────────────────────────────
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
  };
  services.blueman.enable = true;

  # ─────────────────────────────────────────────────────────────────────────────
  # VIRTUALISATION — KVM / QEMU / libvirt
  # ─────────────────────────────────────────────────────────────────────────────
  #virtualisation.kvm.enable = true;
  # ─────────────────────────────────────────────────────────────────────────────
  # UNFREE PACKAGES (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # This allows unfree packages at the system configuration level.
  # Home Manager's gnome.nix has its own allowUnfree for user-level packages.
  # Both are needed — they operate in different package scopes.
  nixpkgs.config.allowUnfree = true;

  # ─────────────────────────────────────────────────────────────────────────────
  # CLAUDE DESKTOP
  # ─────────────────────────────────────────────────────────────────────────────
  # Register the claude-desktop overlay at the system level.
  # This patches pkgs so that pkgs.claude-desktop exists everywhere —
  # in system config AND in Home Manager modules that receive the same pkgs.
  nixpkgs.overlays = [
    inputs.claude-desktop.overlays.default
  ];

  # ─────────────────────────────────────────────────────────────────────────────
  # ALLOWED UNTRUSTED PACKAGES
  # ─────────────────────────────────────────────────────────────────────────────
  nixpkgs.config.permittedInsecurePackages = [ "ventoy-1.1.10" ];

  # ─────────────────────────────────────────────────────────────────────────────
  # NIX SETTINGS
  # ─────────────────────────────────────────────────────────────────────────────
  # experimental-features: flakes and nix-command are not yet stable API in Nix,
  # so they're gated behind this flag. You need both enabled to use flakes.
  # nix-command is the unified `nix` CLI (nix build, nix run, nix shell, etc.).
  nix.settings = {
    experimental-features = [
      "nix-command"
      "flakes"
    ];
    # trusted-users allows cypher-whisperer to run nix as a trusted user —
    # necessary for `home-manager switch` to work with the multi-user daemon.
    trusted-users = [
      "root"
      "cypher-whisperer"
    ];
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # USER ACCOUNT
  # ─────────────────────────────────────────────────────────────────────────────
  # This is the canonical user declaration for cypher-whisperer on NixOS.
  # The uid = 1000 is the universal truth across the CypherOS fleet — every OS
  # recognises this user by UID number, not by username string. File ownership
  # on shared BTRFS subvolumes resolves correctly because UID 1000 is consistent.
  #
  # isNormalUser = true: creates a home directory, adds the user to the
  # 'users' group, and enables login. (As opposed to a system user.)
  #
  # extraGroups: the groups that give this user elevated access to hardware
  # and services. Each group is explained inline.
  users.users.cypher-whisperer = {
    isNormalUser = true;
    uid = 1000;
    description = "Cypher Whisperer";
    home = "/home/cypher-whisperer";
    shell = pkgs.zsh;
    extraGroups = [
      "wheel" # sudo access
      "networkmanager" # manage network connections without sudo
      "docker" # run docker without sudo
      "podman" # rootless podman group (created by containers.nix)
      "audio" # direct audio device access (belt-and-suspenders with PipeWire)
      "video" # GPU/video device access
      "input" # input device access (needed for some Wayland compositors)
      "disk" # disk operations, such as using ventoy
      "adbusers" # android development and emulation with adb
      "libvirtd"
      "kvm" # Virtualization with KVM and qemu
    ];
  };

  # mutableUsers = false would make NixOS the sole authority on users —
  # passwd and adduser commands would be ignored. We'll Leave it true (the default)
  # for now since we may want to change passwords interactively. Revisit in
  # the hardening phase.
  # users.mutableUsers = false;

  # ─────────────────────────────────────────────────────────────────────────────
  # USER AVATAR (AccountsService)
  # ─────────────────────────────────────────────────────────────────────────────
  # AccountsService is the D-Bus daemon that GDM and the lock screen use to
  # display the user tile (name + avatar). It reads from a root-owned system path that
  # home.file cannot touch. An activationScript runs as root
  # during nixos-rebuild switch, so it can write there.
  #
  # The source path references the asset co-located with this flake — hermetic,
  # no manual copying needed.
  system.activationScripts.userAvatar = {
    text = ''
          install -Dm644 ${../../modules/de/assets/default-gnome-avatar.jpg} \
            /var/lib/AccountsService/icons/cypher-whisperer
          # AccountsService also needs a config file pointing at the icon
          mkdir -p /var/lib/AccountsService/users
          cat > /var/lib/AccountsService/users/cypher-whisperer <<EOF
      [User]
      Icon=/var/lib/AccountsService/icons/cypher-whisperer
      EOF
    '';
  };

  # ─────────────────────────────────────────────────────────────────────────────
  # GDM BLURRED BACKGROUND
  # ─────────────────────────────────────────────────────────────────────────────
  # GDM runs its own isolated gnome-shell instance — user extensions (including
  # blur-my-shell) never run there. The only way to set a GDM background is to
  # patch the gnome-shell gresource file that GDM reads.
  #
  # Strategy (activation script, not overlay):
  #   - Runs against the already-built gnome-shell binary — no source rebuild.
  #   - Extracts the gresource, swaps the background image, recompiles it into
  #     a writable system path that gdm reads first.
  #   - Runs on every nixos-rebuild switch; idempotent.
  #   - We write to /etc/gnome-shell-gdm-theme/ and point GDM at it via a
  #     gnome-shell CSS override.
  #
  # PREREQUISITE: generate the blurred image once:
  #   nix-shell -p imagemagick --run \
  #     "convert modules/de/assets/default-gnome-bg.jpg -blur 0x18 modules/de/assets/default-gdm-bg.jpg"
  #system.activationScripts.gdmBackground = {
  #  deps = [ "users" ];
  #  text = let
  #    gnomeShellGresource =
  #      "${pkgs.gnome-shell}/share/gnome-shell/gnome-shell-theme.gresource";
  #    blurredBg = ../../modules/de/assets/default-gdm-bg.jpg;
  #    gresource = "${pkgs.glib.dev}/bin/gresource";
  #    glib-compile = "${pkgs.glib}/bin/glib-compile-resources";
  #  in ''
  #    # Bail out gracefully if tools aren't present rather than failing activation
  #    if [ ! -f ${gresource} ]; then
  #      echo "gdmBackground: gresource not found, skipping" >&2
  #      exit 0
  #    fi

  #    WORKDIR=$(mktemp -d)
  #   trap "rm -rf $WORKDIR" EXIT

  #    for r in $(${gresource} list ${gnomeShellGresource}); do
  #      rel=''${r#/org/gnome/shell/}
  #      mkdir -p "$WORKDIR/''${rel%/*}"
  #      ${gresource} extract ${gnomeShellGresource} "$r" \
  #        > "$WORKDIR/$rel"
  #    done

  #    cp ${blurredBg} "$WORKDIR/theme/noise-texture.png"

  #    mkdir -p /etc/gnome-shell-gdm-theme
  #    ${glib-compile} \
  #      --target="/etc/gnome-shell-gdm-theme/gnome-shell-theme.gresource" \
  #      --sourcedir="$WORKDIR" \
  #      "$WORKDIR/gnome-shell-theme.gresource.xml"
  #  '';
  #};

  # Override the GDM gnome-shell gresource path via an environment variable
  # injected into the GDM session.
  #systemd.services.gdm.environment = {
  #GNOME_SHELL_THEME_DIR = "/etc/gnome-shell-gdm-theme";

  # Honest note: The GNOME_SHELL_THEME_DIR env var approach may or may not be
  # respected depending on your gnome-shell version — this is the part that's
  # genuinely version-sensitive. If it doesn't take effect, the fallback is a
  #  symlink override:
  # ln -sf /etc/gnome-shell-gdm-theme/gnome-shell-theme.gresource \
  #   ${pkgs.gnome-shell}/share/gnome-shell/gnome-shell-theme.gresource
  #— but that writes into the store (read-only). The cleanest alternative at
  # that point is a services.xserver.displayManager.gdm.extraConfig-style
  # approach or a bind mount.
  #};

  # ─────────────────────────────────────────────────────────────────────────────
  # ZSH (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # Setting the user shell to pkgs.zsh above requires zsh to be enabled at the
  # system level — NixOS won't add it to /etc/shells otherwise, which breaks login.
  programs.zsh.enable = true;

  # ─────────────────────────────────────────────────────────────────────────────
  # SYSTEM PACKAGES
  # ─────────────────────────────────────────────────────────────────────────────
  # Packages listed here are installed system-wide (available to all users,
  # in the system PATH). 
  # Keep this minimal — user-space apps belong in Home Manager, not here.
  #
  # What belongs here: tools needed before Home Manager runs, or tools that
  # genuinely require system-level installation.
  environment.systemPackages = with pkgs; [
    git          # needed to clone the cypher-system flake repo itself
    curl         # needed for initial Nix/HM bootstrap commands
    vim          # emergency editor before HM applies neovim
    home-manager # the home-manager CLI must be on the system PATH
    os-prober    # for detecting other OSs in a multi-boot setup

    glib # needed for gdmBackground activation script
  ];

  # ─────────────────────────────────────────────────────────────────────────────
  # FONTS (SYSTEM LEVEL)
  # ─────────────────────────────────────────────────────────────────────────────
  # Fonts declared here are available system-wide (GDM login screen, all users).
  # User fonts (in Home Manager) are in addition to these.
  fonts.fontDir.enable = true;
  fonts.enableGhostscriptFonts = true;
  fonts.packages = with pkgs; [
    cantarell-fonts
    noto-fonts
    noto-fonts-color-emoji 
    #(nerdfonts.override {
    #  fonts = ["JetBrainsMono"];  
    # })
    # As of November 2024, the nerdfonts package has been separated into 
    # individual packages under the namespace nerd-fonts. If your system throws
    # errors or warnings about terminus-nerdfont being redundant, you should 
    # replace the override method with the specific package:
    nerd-fonts.jetbrains-mono

    #fira-code
    nerd-fonts.fira-code        # Fira Code: 
    nerd-fonts.hack             # Hack: 
    #nerd-fonts.source-code-pro  # Source Code Pro: 
    #nerd-fonts.cascadia-code    # Cascadia Code: 
    #nerd-fonts.iosevka          # Iosevka: 
    #nerd-fonts.victor-mono      # Victor Mono: 
    nerd-fonts.jetbrains-mono   # JetBrains Mono: 
    nerd-fonts.lilex            # Lilex: 
    nerd-fonts.monaspace        # Monaspace: 
    nerd-fonts.noto             # Noto: 
    nerd-fonts.roboto-mono      # Roboto Mono: 
    nerd-fonts.ubuntu-mono      # Ubuntu Mono: 
    #nerd-fonts.meslo-lg         # Meslo LG: 
    nerd-fonts.sauce-code-pro   # Sauce Code Pro: 
  ];

  # ─────────────────────────────────────────────────────────────────────────────
  # SYSTEM STATE VERSION
  # ─────────────────────────────────────────────────────────────────────────────
  # Like home.stateVersion in gnome.nix, this is set once at install time and
  # never changed. It tells NixOS which release the system config was written
  # against. It does NOT control which package versions you get — that's
  # determined by your flake inputs (the nixpkgs pin in flake.lock).
  system.stateVersion = "24.11";
}
