# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/be538557-3745-48c3-8980-7260af4a1de0";
      fsType = "btrfs";
      options = [ "subvol=@nixos-root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/8355-B4F9";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/be538557-3745-48c3-8980-7260af4a1de0";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/cypher-whisperer/DATA" =
    { device = "/dev/disk/by-uuid/be538557-3745-48c3-8980-7260af4a1de0";
      fsType = "btrfs";
      options = [ "subvol=@data" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/be538557-3745-48c3-8980-7260af4a1de0";
      fsType = "btrfs";
      options = [ "subvol=@nix-store" ];
    };

  fileSystems."/swap" =
    { device = "/dev/disk/by-uuid/be538557-3745-48c3-8980-7260af4a1de0";
      fsType = "btrfs";
      options = [ "subvol=@swap" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
