# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/74e9ae87-4ab3-4312-8202-2bbb633e39b0";
      fsType = "btrfs";
      options = [ "subvol=@nixos-root" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/3DE5-FF97";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/74e9ae87-4ab3-4312-8202-2bbb633e39b0";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/DATA" =
    { device = "/dev/disk/by-uuid/74e9ae87-4ab3-4312-8202-2bbb633e39b0";
      fsType = "btrfs";
      options = [ "subvol=@data" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/74e9ae87-4ab3-4312-8202-2bbb633e39b0";
      fsType = "btrfs";
      options = [ "subvol=@nix-store" ];
    };

  swapDevices =
    [ { device = "/dev/disk/by-uuid/866454b6-51a8-4c56-aeae-068d2ecafaf4"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
