# modules/arduino/hm.nix
#
# Home Manager configuration for the Arduino / IoT subsystem.
#
# WHAT THIS FILE OWNS:
#   - User-level package installation (arduino-cli, LSP toolchain, serial monitors)
#   - arduino-cli declarative config (xdg.configFile → ~/.config/arduino-cli/arduino-cli.yaml)
#
# WHAT THIS FILE DOES NOT OWN:
#   - System packages / udev / group config  → system.nix
#   - Shell aliases                          → modules/shell/zsh.nix
#                                              (reads cypher-os.arduino.* options directly)
#   - Neovim LSP integration                 → modules/editors/neovim/lsp.nix (or equivalent)
#                                              (see CypherIDE LSP integration note below)
#   - VSCode extension                       → modules/apps/editor/vscode.nix
#                                              (see VSCode integration note below)
#   - Option declarations                    → options.nix
#
# ── NEOVIM / CYPHERIDE LSP INTEGRATION NOTE ──────────────────────────────────
#   This module installs arduino-language-server and clangd into the user
#   environment (home.packages below). The Neovim LSP wiring is handled
#   separately in the CypherIDE lsp plugin module — not here — to respect
#   the separation between tool installation and editor configuration.
#
#   NOTE: for the CypherIDE wiring; the key facts it needs:
#     - Server binary:  arduino-language-server (in PATH via home.packages)
#     - CLI binary:     arduino-cli             (in PATH via home.packages)
#     - CLI config:     ~/.config/arduino-cli/arduino-cli.yaml
#                       (deployed by xdg.configFile below)
#     - Clangd binary:  clangd                  (in PATH via home.packages)
#     - Board FQBN:     config.cypher-os.arduino.fqbn
#                       (read from options — pass it into the LSP cmd args)
#
#   The LSP server only attaches to .ino files and requires a sketch.yaml
#   in the project root. See the SKETCH CONVENTION note further below.
#
# ── VSCODE INTEGRATION NOTE ──────────────────────────────────────────────────
#   Add the Arduino Community Edition extension in vscode.nix Tier 2:
#
#     vscMkt.vscjava.vscode-arduino
#
#   NOTE: Do NOT use vscMkt.ms-vscode.vscode-arduino — that is Microsoft's
#   deprecated extension which does not support Arduino IDE 2.x / arduino-cli
#   properly. The community edition (vscjava) is the maintained successor.
#
#   To Add to the sharedSettings attrset in vscode.nix:
#
#     # ── Language: Arduino ──────────────────────────────────────────────────
#     # arduino-cli is the backend for both compile and upload operations.
#     # The extension resolves the binary from $PATH — no absolute path needed
#     # because vscode.fhs (if in use) inherits the user PATH.
#     # If on plain pkgs.vscode (non-FHS), arduino-cli works fine since it is
#     # a statically-linked Go binary; only extensions with native .node
#     # addons need FHS. Switch to vscode.fhs only if the extension's serial
#     # monitor bridge fails with a dynamic linker error.
#     "arduino.useArduinoCli"       = true;
#     "arduino.commandPath"         = "arduino-cli";
#     "arduino.logLevel"            = "info";
#     "arduino.clearOutputOnBuild"  = true;
#     "arduino.defaultBaudRate"     = 9600;
#
#   Per-workspace arduino.json (auto-generated by the extension on first use):
#     { "board": "arduino:avr:uno", "port": "/dev/ttyACM0", "sketch": "MySketch.ino" }
#   Keep this file out of .gitignore if you want port/board settings versioned.
#
# ── SKETCH CONVENTION NOTE ───────────────────────────────────────────────────
#   The arduino-language-server requires a sketch.yaml in the project root
#   to understand which board the sketch targets. Without it the LSP will
#   not attach (no error — it simply won't start).
#
#   Generate it for a new sketch:
#     arduino-cli sketch new MySketch
#     # Creates MySketch/MySketch.ino and MySketch/sketch.yaml
#
#   Or write it manually (minimum viable):
#     # MySketch/sketch.yaml
#     default_fqbn: arduino:avr:uno
#     default_port: /dev/ttyACM0
#
#   Required project layout (.ino filename must match folder name):
#     ~/Projects/arduino/
#     └── MySketch/
#         ├── MySketch.ino   ← main sketch
#         └── sketch.yaml    ← LSP board descriptor
#
#   The sketch directory is set to ~/Projects/arduino by the arduino-cli config
#   below (directories.user). All new sketches created via `arduino-cli sketch
#   new` will land there automatically.
#
# ── POST-SWITCH IMPERATIVE STEPS ─────────────────────────────────────────────
#   These are user-space follow-ups after `nixos-rebuild switch` or
#   `home-manager switch`. They are imperative because arduino-cli downloads
#   board toolchains at runtime from Arduino's CDN — Nix cannot hash-pin them
#   at evaluation time without a per-board fixed-output derivation (see the
#   arduino-nix community project for that approach; out of scope here).
#
#   1. Update the package index (fetches the board/library index JSON):
#        arduino-cli core update-index
#
#   2. Install the AVR core (Arduino Uno, Nano, Mega and most starter boards):
#        arduino-cli core install arduino:avr
#
#      For ESP32 / ESP8266: first add the board manager URL to the
#      additional_urls list in the arduino-cli config below, rebuild HM,
#      then install the core:
#        # ESP32
#        arduino-cli core install esp32:esp32
#        # ESP8266
#        arduino-cli core install esp8266:esp8266
#
#   3. Verify the board is detected (plug it in first):
#        arduino-cli board list
#
#   4. Verify the language server binary chain:
#        arduino-language-server --help    # should print usage
#        clangd --version                  # should print version
#        arduino-cli version               # should print version
#
#   5. Create your first sketch and confirm the LSP attaches in Neovim:
#        arduino-cli sketch new Blink
#        cd ~/Projects/arduino/Blink
#        nvim Blink.ino                    # LSP should attach within ~2s

{
  config,
  pkgs,
  lib,
  ...
}:

let
  cfg = config.cypher-os.arduino;
in
lib.mkIf cfg.enable {

  # ── User-level packages ────────────────────────────────────────────────────
  # arduino-cli: also installed at system level (system.nix) for udev
  #   rule discovery. Nix deduplicates the store path — no overhead.
  #
  # arduino-language-server: the LSP server for .ino files. It wraps
  #   arduino-cli (for compilation and board queries) and clangd (for
  #   C++ indexing). Both must be in PATH for it to start correctly.
  #   The server is board-specific: it re-indexes when -fqbn changes.
  #   Managed here (not via Mason) because Mason cannot patch NixOS
  #   binaries — all tool resolution goes through the Nix store.
  #
  # clang-tools: provides clangd. arduino-language-server calls clangd
  #   as a subprocess; it must be the same clangd the LSP was linked against.
  #   Using nixpkgs clang-tools ensures version coherence.
  #
  # screen / minicom: lightweight serial monitors for quick debugging
  #   without opening an IDE. See serial monitor cheatsheet below.
  #
  # ── Ruled-out user packages ───────────────────────────────────────────────
  # pkgs.arduino-mk: Makefile build system. arduino-cli covers the same
  #   workflow more ergonomically. Omitted.
  # pkgs.arduinoOTA: installed at system level when ota.enable is true.
  #   Not repeated here.
  home.packages = with pkgs; [
    arduino-cli
    arduino-language-server
    clang-tools # provides clangd (required by language server)
    screen
    # serial monitor: screen /dev/ttyACM0 9600
    # quit: Ctrl-A then K
    minicom
    # serial monitor with line history and better UX
    # quit: Ctrl-A then X  launch: minicom -D /dev/ttyACM0 -b 9600
  ];

  # ── arduino-cli declarative configuration ─────────────────────────────────
  # Deployed to ~/.config/arduino-cli/arduino-cli.yaml.
  # arduino-cli reads this path when the ARDUINO_DIRECTORIES_DATA env var
  # is unset, which is our case (we don't override it in zsh.nix).
  #
  # directories.user: where `arduino-cli sketch new` places new sketches.
  #   Points to ~/Projects/arduino — adjust if your project root differs.
  # directories.data / downloads: XDG-aligned paths keep the home
  #   directory clean and avoid the default ~/.arduino15 scatter.
  #
  # additional_urls: add third-party board manager URLs here;
  #   ESP32 / ESP8266 / other non-AVR boards, then
  #   rebuild HM and run `arduino-cli core update-index` again.
  #   Example URLs (add as list items, uncomment as needed):
  #     - https://arduino.esp8266.com/stable/package_esp8266com_index.json
  #     - https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json
  #
  # metrics.enabled / updater.enable_notification: both set to false —
  #   consistent with the telemetry-off posture across CypherOS.
  xdg.configFile."arduino-cli/arduino-cli.yaml" = {
    text = ''
      board_manager:
        additional_urls: []
      daemon:
        port: "50051"
      directories:
        data: ${config.home.homeDirectory}/.local/share/arduino-cli
        downloads: ${config.home.homeDirectory}/.local/share/arduino-cli/staging
        user: ${config.home.homeDirectory}/Projects/arduino
      logging:
        file: ""
        format: text
        level: info
      metrics:
        addr: :9090
        enabled: false
      sketch:
        always_export_binaries: false
      updater:
        enable_notification: false
    '';
  };
}
